### ISSUE TITLE
how to run acousticCameraSimulator.m without .mat config

### ISSUE THREAD

**Issue by iPwnXX** [jorgengrythe/beamforming#4]
Since the data/array/*.mat isn't allowed to be provided,  how to run or test the acousticCameraSimulator.m?  since it requires the mic array geometry configuration.

**Comment by jorgengrythe** [comment]
The .mat files were removed since some of the information was company confidential. The .mat files basically contained x, y, z positions of array geometry and also array weights (w). It will take some editing of the function to make it work, but you should be able to make your own different array geometries (xPos, yPos, zPos and w) and save them in different .mat files. They are used in the call to the function changeArray (that just loads the xPos, yPos, zPos and w vectors), and are referenced in the addContextMenu function.

For instance this is how you create the vectors you need for a circular array
nElements = 20;
radius = 0.6;
[xPos, yPos] = pol2cart((0:1/nElements:1-1/nElements)*2*pi, ones(1,nElements)*radius);
zPos = zeros(1, numel(xPos));
w = ones(1,numel(xPos))/numel(xPos);

and then you save xPos, yPos, zPos and w in a new .mat file and add a reference to the .mat filename in the addContextMenu function
